FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

RUN apt-get update
RUN apt-get install --no-install-recommends -y
RUN apt-get -y install gss-ntlmssp
RUN apt-get -y install apt-utils

COPY . .

RUN dotnet restore "test/Mch.Internal.UnifiedContextDb.Test_Net8/Mch.Internal.UnifiedContextDb.Test_Net8.csproj"

RUN dotnet build "test/Mch.Internal.UnifiedContextDb.Test_Net8/Mch.Internal.UnifiedContextDb.Test_Net8.csproj" -c Release -o /app/build --no-restore

FROM build AS test

RUN dotnet test test/Mch.Internal.UnifiedContextDb.Test_Net8/Mch.Internal.UnifiedContextDb.Test_Net8.csproj --logger "trx;LogFileName=testresults.trx" --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true;exit 0
RUN dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.6
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN export PATH="$PATH:/root/.dotnet/tools"

RUN reportgenerator -reports:test/Mch.Internal.UnifiedContextDb.Test_Net8/TestResults/**/*.xml -targetdir:TestResults/coverlet/reports -reporttypes:"Cobertura"

FROM scratch AS export-stage
COPY --from=test /test/Mch.Internal.UnifiedContextDb.Test_Net8/TestResults /testresults